server:
  port: 6000
  servlet:
    encoding:
      charset: utf-8
      force: true

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{mysql.database.azure.com}/{database}
#    username: root
#    password: root
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      '[hibernate.default_batch_fetch_size]': 100

  logging:
    level:
      org:
        hibernate:
          SQL: INFO
